def developer3method():
    print("FirstName: Jasurbek")
    print("Surname: Sadiev")
    print("Email: jasursadiev2002@gmail.com")
    print("Cohort: Computer Science")
    print("Age: 20")
    print("gender: male")
    print("BirthDate: 19.04.2002")
    print("Specialty: Computer Scientist")
    print("Country: Tajikistan")
    print("Hello WOrld")
